apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-expense-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: split-expense-backend
  template:
    metadata:
      labels:
        app: split-expense-backend
    spec:
      containers:
        - name: backend
          image: chaiiiram/split-expense-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: MONGO_URI
              value: "mongodb+srv://sai:Sai123@cluster0.rkzsqre.mongodb.net/splitappdb?retryWrites=true&w=majority"
            - name: JWT_SECRET
              value: "supersecretkey123"
