apiVersion: v1
kind: Service
metadata:
  name: split-expense-backend-service
spec:
  type: ClusterIP
  selector:
    app: split-expense-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
