apiVersion: v1
kind: Service
metadata:
  name: split-expense-frontend-service
spec:
  type: NodePort
  selector:
    app: split-expense-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
